### ISSUE TITLE
add tag access restrictions

### ISSUE THREAD

**Issue by JKHeadley** [cusac/mbt.guide-backend#42]
The update and delete tag endpoints should only be accessible by Admin users.

Here are the docs for authorization in rest-hapi: https://resthapi.com/docs/authorization.html
And more specific authorization docs for our user system can be found here: https://github.com/JKHeadley/appy-backend/wiki/Authorization

Currently, I believe the only role-based authorization restrictions we enforce are for segments at a document specific level:

https://github.com/cusac/mbt.guide-backend/blob/86df6c20c7578e43743458ed68d9a16babfd3670/server/models/segment.model.js#L55

**Comment by franksmicro** [comment]
I am having difficulty reproducing this issue.

I am running against a local copy of the database.  When I attempt to call either the API Delete or Update functionality using a token for an ordinary user (test@user.com), I get a "403 - Forbidden - Insufficient permissions" response.  Calling Delete and Update both work using the token from an editor (test@editoradmin.com).  I tried other users as well, and the determining factor for being able to delete/update seems to be the role "Admin" for the user.

I am able to query tags as anyone (in fact, I don't even need a user token), but I don't think this is an issue.

Let me know if the above behavior is incorrect, or if additional restrictions are needed.

**Comment by JKHeadley** [comment]
@franksmicro Thanks for looking into this. Looks like you are correct. It seems that at some point we added the correct permissions to the Admin role, so there's no need to modify the route itself.
